export enum SpecialitiesName {
  Anesthesiologist,
  Dentist,
  Dermatologist,
  Gynecologist,
  Neurologist,
  Obstetrician,
  Oncologist,
  Ophthalmologist,
  Pathologist,
  Pediatrician,
  Psychiatrist,
  Radiologist,
  Surgeon,
  Traumatologist,
  Urologist,
}
